### ISSUE TITLE
error about "input = x['input_ids'].to(self.device).squeeze(0)"

### ISSUE THREAD

**Issue by pengqianhan** [Zhang-Yihao/Transfomer2WFA#1]
Hi 
when I run the [DFA_RNN.ipynb](https://github.com/Zhang-Yihao/Transfomer2DFA/blob/new/DFA_RNN.ipynb)
I encountered a problem with dimensions. After debugging, I identified the error in the following code.
'''
bert_output = self.model.bert(x['input_ids'].to(transformer.device)).pooler_output
input = x['input_ids'].to(self.device).squeeze(0)
'''
 the code should be 
'''
bert_output = self.model.bert(x['input_ids'].to(transformer.device)).pooler_output
input = x['input_ids'].to(self.device)
'''
Hope this helps.

**Comment by Zhang-Yihao** [comment]
Thanks a lot!!!!!!!! I am still reorganizing this repo, and some typos and temporary statements might be used during the testing phase. I will merge your corrections soon. Please feel free to tell me if any other issue is found in my code!!!
